# Generated by Django 4.1.7 on 2023-12-24 19:26

from django.db import migrations, models
import models_app.utils.file_uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_file', models.FileField(blank=True, null=True, upload_to=models_app.utils.file_uploader.uploaded_file_path, verbose_name='Imported File')),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
                'db_table': 'history',
            },
        ),
    ]
